COIN_DICT = {
    "BTC": "Bitcoin", 
    "Bitcoin":"Bitcoin", 
    "ETH": "Ethereum", 
    "Ethereum":"Ethereum", 
    "BCH": "Bitcoin Cash", 
    "Bitcoin Cash": "BCH", 
    "Litecoin":"Litecoin", 
    "LTC": "Litecoin", 
    "Chainlink": "Chainlink",
     "LINK": "Chainlink", 
     "USDT": "Tether", 
     "Tether": "Tether", 
     "Cardano":"ADA", 
     "ADA":"Cardano", 
     "Binance Coin":"BNB", 
     "BNB":"Binance Coin", 
     "Polkadot": "DOT", 
     "DOT":"Polkadot",
     "XRP": "XRP",
     "UNI":"Uniswap",
     "Uniswap":"Uniswap",
     "Stellar":"Stellar",
     "XLM": "Stellar",
     "USD Coin": "USDC",
     "USDC": "USD Coin",
     "NEM": "NEM",
     "XEM": "NEM",
     "FOR": "ForTube",
     "ForTube": "ForTube"
     }

FILTER_LIST = [
    "strong",
    "meme",
    "up", 
    "real", 
    "pre", 
    "gem", 
    "free",
    "safe",
    "own",
    "easy",
    "nano",
    "swap",
    "get",
    "id",
    "a",
    "the",
    "via",
    "ama",
    "token",
    "just",
    "s",
    "on",
    "its",
    "can",
    "buy",
    "me",
    "like",
    "it",
    "now",
    "fair",
    "launch",
    "for",
    "new",
    "coin",
    "you",
    "any",
    "dev",
    "rise",
    "time",
    "diamond",
    "at",
    "one",
    "chess"
    ] 
