COIN_DICT = {
    "btc": "Bitcoin", 
    "bitcoin":"Bitcoin", 
    "eth": "Ethereum", 
    "ethereum":"Ethereum", 
    "bch": "Bitcoin Cash", 
    "bitcoin cash": "BCH", 
    "litecoin":"Litecoin", 
    "ltc": "Litecoin", 
    "chainlink": "Chainlink",
     "link": "Chainlink", 
     "usdt": "Tether", 
     "tether": "Tether", 
     "cardano":"ADA", 
     "ada":"Cardano", 
     "binance coin":"BNB", 
     "bnb":"Binance Coin", 
     "polkadot": "DOT", 
     "dot":"Polkadot",
     "xrp": "XRP",
     "uni":"Uniswap",
     "uniswap":"Uniswap",
     "stellar":"Stellar",
     "xlm": "Stellar",
     "usd coin": "USDC",
     "usdc": "USD Coin",
     "nem": "NEM",
     "xem": "NEM",
     "for": "ForTube",
     "fortube": "ForTube"
     }

FILTER_LIST = [
    "strong",
    "meme",
    "up", 
    "real", 
    "pre", 
    "gem", 
    "free",
    "safe",
    "own",
    "easy",
    "nano",
    "swap",
    "get",
    "id",
    "a",
    "the",
    "via",
    "ama",
    "token",
    "just",
    "s",
    "on",
    "its",
    "can",
    "buy",
    "me",
    "like",
    "it",
    "now",
    "fair",
    "launch",
    "for",
    "new",
    "coin",
    "you",
    "any",
    "dev",
    "rise",
    "time",
    "diamond",
    "at",
    "one",
    "chess"
    ] 
