COIN_DICT = {
    "BTC": "Bitcoin", 
    "Bitcoin":"Bitcoin", 
    "ETH": "Ethereum", 
    "Ethereum":"Ethereum", 
    "BCH": "Bitcoin Cash", 
    "Bitcoin Cash": "BCH", 
    "Litecoin":"Litecoin", 
    "LTC": "Litecoin", 
    "Chainlink": "Chainlink",
     "LINK": "Chainlink", 
     "USDT": "Tether", 
     "Tether": "Tether", 
     "Cardano":"ADA", 
     "ADA":"Cardano", 
     "Binance Coin":"BNB", 
     "BNB":"Binance Coin", 
     "Polkadot": "DOT", 
     "DOT":"Polkadot",
     "XRP": "XRP",
     "UNI":"Uniswap",
     "Uniswap":"Uniswap",
     "Stellar":"Stellar",
     "XLM": "Stellar",
     "USD Coin": "USDC",
     "USDC": "USD Coin",
     "NEM": "NEM",
     "XEM": "NEM"
     }